### ISSUE TITLE
Last run date is updated before the job runs to completion (or failure)

### ISSUE THREAD

**Issue by jezdez** [mozilla/telemetry-analysis-service#205]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1316042

**Comment by jezdez** [comment]
@robhudson With the work in #189, do you think we can close this as invalid, or is this something that will be fixed there?

**Comment by robhudson** [comment]
The solution we talked about was to renamed `last_run_date` to `scheduled_date` and put it on the historical runs table. Then add separate date fields for the main life cycles of the cluster status (run_date and terminated_date) since these are already being checked every minute.

The first part will be done in #189. I could add the extra fields there also if preferred and with that I would consider this fixed by that PR.

**Comment by robhudson** [comment]
Closed as part of #189
