### ISSUE TITLE
Ad-hoc clusters should wait for configuration steps to complete

### ISSUE THREAD

**Issue by vitillo** [mozilla/telemetry-analysis-service#256]
Our [bootstrap script](https://github.com/mozilla/emr-bootstrap-spark/blob/35da8c5b041f007efe0d0f5c728866aba59f7e0b/ansible/files/bootstrap/telemetry.sh) is quite bloated; it would be nice to split it up in several steps that happen after the cluster has been spun up by AWS. For example, since the bootstrap script is invoked before Presto is installed, in order to load Parquet tables it has to spawn a background process that [checks periodically](https://github.com/mozilla/emr-bootstrap-spark/blob/35da8c5b041f007efe0d0f5c728866aba59f7e0b/ansible/files/bootstrap/telemetry.sh#L150) the status of the Hive metastore.

The recently introduced Zeppelin configuration step goes into that direction. Ideally the cluster should be considered ready only when it has reached the waiting state.

**Comment by jezdez** [comment]
@vitillo That's a great idea, I always wondered why everything is covered by the bootstrap script and not by additional steps. And this fits nicely with #203. My goal there was to split up the script in smaller ones so that we can more easily debug them in isolation, steps for a "base setup", "python env", "telemetry dependencies" etc. Do you think we should eventually make it possible to publish that ability to users, being able to add new steps on their own, writing scripts etc? I think #204 would basically a use case for this.

**Comment by vitillo** [comment]
> Do you think we should eventually make it possible to publish that ability to users, being able to add new steps on their own, writing scripts etc? I think #204 would basically be a use case for this.

Yes, that would be very useful not only to our users but also to us to easily test new steps.

**Comment by vitillo** [comment]
Looks like the service is already [doing](https://github.com/mozilla/telemetry-analysis-service/blob/9fd6c159d85e962596e4d3e7c080b01f5c8b4557/atmo/clusters/models.py#L134) the right [thing](https://github.com/mozilla/telemetry-analysis-service/blob/23a684ecd622931bf89ba0f0b1b3a48a436d3cc7/atmo/templates/atmo/clusters/detail.html#L29).
