### ISSUE TITLE
Create view with jobs histories

### ISSUE THREAD

**Issue by vitillo** [mozilla/telemetry-analysis-service#271]
There have been several jobs failing silently. Those jobs will soon generate alerts (#201) but it would  still be convenient to have a master view in the dashboard that shows the history, and their status, of all scheduled jobs.  Furthermore, every user should be able to see the history for their own jobs.

**Comment by jezdez** [comment]
@vitillo Yep, another tab on the job detail page makes sense for the list of runs and their status. In fact the work on #201 is providing much of this and I'm far with the implementation so that we should finish that first and then extend that work to implement this feature request.

Would you consider showing the scheduled jobs of *all users* for admins in the dashboard useful? We have the permission system in place to enable the ability to do that.

**Comment by vitillo** [comment]
> Would you consider showing the scheduled jobs of all users for admins in the dashboard useful? We have the permission system in place to enable the ability to do that.

Yes, in fact this is the view I was referring to in my comment.

**Comment by jezdez** [comment]
@vitillo Cool, I've opened #283 to track this separate issue then and leave this open for showing the history on the job detail page.
