### ISSUE TITLE
`top-signatures-correlations` job was not scheduled/run on 2017-03-19

### ISSUE THREAD

**Issue by marco-c** [mozilla/telemetry-analysis-service#326]
My scheduled job (`top-signatures-correlations`) was not scheduled nor run on 2017-03-19.

**Comment by marco-c** [comment]
See also #351.

Do you think #372 will fix these issues?

**Comment by marco-c** [comment]
At the moment, the last run time is 2017/04/04 at 11:40 UTC (checked by @fbertsch). I've scheduled it twice after that, but it didn't run.
I've also tried to remove the scheduled job and recreate it, but it didn't run anyway.

**Comment by jezdez** [comment]
@marco-c So I've done some digging yesterday and I think I found the underlying issue, basically the way ATMO currently works (unintentionally) let's the time window when the job is supposed to be executed slip due to our naive cron implementation (that uses the last successful run as the base datetime for running the next one, and not the saved start date) on top of the massive API throttling that Amazon does for our system.

We've requested a raise for the throttle limits but were told that it can't be raised. We've already implemented the strategy (exponential back-off retries) that AWS recommended to us. That means we have no other way out other than rethinking the way we schedule the jobs in the first place (e.g. #332, #372).

I've prioritized #372 now and will also solve #332 to reduce the chance that a system hiccup via API throttling prevents the job to execute.

**Comment by rafrombrc** [comment]
#372 has been completed, target deployment on 2017/04/27, we'll come back and verify that it did indeed fix this issue after the deployment, more soon.

**Comment by marco-c** [comment]
It was executed tonight.

**Comment by rafrombrc** [comment]
Great, thanks! Closing this issue.

**Comment by marco-c** [comment]
I have another scheduled job which is behaving strangely, `top-fennec-signatures-correlations`.
It looks like in the past few days (since April 27) it has been running twice a day, with the two runs really close to each other:
```
top-fennec-signatures-correlations/logs/top-fennec-signatures-correlations.20170429233705.log.gz
top-fennec-signatures-correlations/logs/top-fennec-signatures-correlations.20170429233422.log.gz
top-fennec-signatures-correlations/logs/top-fennec-signatures-correlations.20170428233436.log.gz
top-fennec-signatures-correlations/logs/top-fennec-signatures-correlations.20170428233405.log.gz
top-fennec-signatures-correlations/logs/top-fennec-signatures-correlations.20170427233629.log.gz
top-fennec-signatures-correlations/logs/top-fennec-signatures-correlations.20170427233600.log.gz
top-fennec-signatures-correlations/logs/top-fennec-signatures-correlations.20170426232925.log.gz
top-fennec-signatures-correlations/logs/top-fennec-signatures-correlations.20170425232508.log.gz
top-fennec-signatures-correlations/logs/top-fennec-signatures-correlations.20170424231945.log.gz
top-fennec-signatures-correlations/logs/top-fennec-signatures-correlations.20170412074012.log.gz
top-fennec-signatures-correlations/logs/top-fennec-signatures-correlations.20170406073501.log.gz 
```

Also, it is scheduled for 11:55 UTC, but it is running at 23:30 UTC.
