### ISSUE TITLE
scheduler terminates early locally

### ISSUE THREAD

**Issue by robhudson** [mozilla/telemetry-analysis-service#407]
This is what I see in the output...

```
scheduler_1  | INFOS:
scheduler_1  | ?: (dockerflow.health.I001) Can't connect to database to check migrations
scheduler_1  | Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fb3f5662bf8>
scheduler_1  | Traceback (most recent call last):
scheduler_1  |   File "/usr/local/lib/python3.5/weakref.py", line 117, in remove
scheduler_1  | TypeError: 'NoneType' object is not callable
scheduler_1  | Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fb3f5662bf8>
scheduler_1  | Traceback (most recent call last):
scheduler_1  |   File "/usr/local/lib/python3.5/weakref.py", line 117, in remove
scheduler_1  | TypeError: 'NoneType' object is not callable
scheduler_1  | System check identified some issues:
```

**Comment by jezdez** [comment]
The scheduler isn't waiting on the database container it seems, which means that the `wait_for` isn't correctly used for it. I know for a fact that the actual script works, so it must be related to the condition we set in the `bin/run` script: We need to make sure the `DEVELOPMENT` env var is set in development, since that's where the `bin/run` script will [wait for it](https://github.com/mozilla/telemetry-analysis-service/blob/0ea7a6f178732a51ca311062d492cf5debee73de/bin/run#L29-L31).
